[2023-10-14T10:55:11.198+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:55:11.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:55:11.204+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:55:11.203+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:55:11.217+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:55:11.213+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:55:11.219+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:55:11.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.079 seconds
[2023-10-14T10:55:41.529+0000] {processor.py:157} INFO - Started process (PID=86) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:55:41.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:55:41.551+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:55:41.547+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:55:41.568+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:55:41.562+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:55:41.569+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:55:41.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.115 seconds
[2023-10-14T10:56:12.237+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:56:12.240+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:56:12.244+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:56:12.244+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:56:12.251+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:56:12.249+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:56:12.251+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:56:12.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.050 seconds
[2023-10-14T10:56:42.424+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:56:42.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:56:42.432+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:56:42.432+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:56:42.439+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:56:42.437+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:56:42.439+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:56:42.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.041 seconds
[2023-10-14T10:57:12.838+0000] {processor.py:157} INFO - Started process (PID=251) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:57:12.841+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:57:12.846+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:57:12.846+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:57:12.853+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:57:12.852+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:57:12.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:57:12.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.041 seconds
[2023-10-14T10:57:43.083+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:57:43.084+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:57:43.092+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:57:43.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:57:43.101+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:57:43.098+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:57:43.102+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:57:43.127+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.054 seconds
[2023-10-14T10:58:13.621+0000] {processor.py:157} INFO - Started process (PID=362) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:58:13.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:58:13.634+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:58:13.634+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:58:13.641+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:58:13.639+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:58:13.641+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:58:13.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.062 seconds
[2023-10-14T10:58:43.906+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:58:43.907+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:58:43.910+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:58:43.910+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:58:43.915+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:58:43.913+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:58:43.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:58:43.933+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.031 seconds
[2023-10-14T10:59:14.062+0000] {processor.py:157} INFO - Started process (PID=471) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:14.064+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:59:14.068+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:59:14.068+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:14.075+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:59:14.073+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:59:14.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:14.118+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.061 seconds
[2023-10-14T10:59:20.793+0000] {processor.py:157} INFO - Started process (PID=512) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:20.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:59:20.796+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:59:20.795+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:20.799+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:59:20.798+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:59:20.799+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:20.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.025 seconds
[2023-10-14T10:59:21.946+0000] {processor.py:157} INFO - Started process (PID=518) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:21.947+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:59:21.949+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:59:21.949+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:21.954+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:59:21.953+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:59:21.954+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:21.973+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.031 seconds
[2023-10-14T10:59:52.863+0000] {processor.py:157} INFO - Started process (PID=573) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:52.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T10:59:52.869+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:59:52.868+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:52.875+0000] {logging_mixin.py:151} INFO - [2023-10-14T10:59:52.873+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T10:59:52.875+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T10:59:52.893+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.035 seconds
[2023-10-14T11:00:23.116+0000] {processor.py:157} INFO - Started process (PID=628) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:00:23.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:00:23.121+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:00:23.120+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:00:23.126+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:00:23.125+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T11:00:23.126+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:00:23.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.030 seconds
[2023-10-14T11:00:53.391+0000] {processor.py:157} INFO - Started process (PID=683) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:00:53.392+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:00:53.395+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:00:53.395+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:00:53.400+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:00:53.399+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T11:00:53.401+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:00:53.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.031 seconds
[2023-10-14T11:01:23.691+0000] {processor.py:157} INFO - Started process (PID=738) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:23.692+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:01:23.694+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:01:23.694+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:23.699+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:01:23.698+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 26
    bash_command='cd src',
    ^
SyntaxError: keyword argument repeated
[2023-10-14T11:01:23.700+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:23.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.031 seconds
[2023-10-14T11:01:51.146+0000] {processor.py:157} INFO - Started process (PID=768) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:51.148+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:01:51.151+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:01:51.151+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:51.158+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:01:51.156+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.operators.python_operator import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators.python_operator' (unknown location)
[2023-10-14T11:01:51.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:51.204+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.063 seconds
[2023-10-14T11:01:54.049+0000] {processor.py:157} INFO - Started process (PID=795) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:54.050+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:01:54.052+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:01:54.052+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:54.058+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:01:54.057+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.operators.python_operator import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators.python_operator' (unknown location)
[2023-10-14T11:01:54.058+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:54.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.028 seconds
[2023-10-14T11:01:58.100+0000] {processor.py:157} INFO - Started process (PID=796) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:58.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:01:58.104+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:01:58.104+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:58.113+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:01:58.112+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.operators.python_operator import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators.python_operator' (unknown location)
[2023-10-14T11:01:58.113+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:01:58.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.042 seconds
[2023-10-14T11:02:28.767+0000] {processor.py:157} INFO - Started process (PID=851) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:28.769+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:02:28.772+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:02:28.771+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:28.778+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:02:28.777+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.operators.python_operator import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators.python_operator' (unknown location)
[2023-10-14T11:02:28.779+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:28.801+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.038 seconds
[2023-10-14T11:02:57.081+0000] {processor.py:157} INFO - Started process (PID=906) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:57.084+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:02:57.087+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:02:57.086+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:57.097+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:02:57.095+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:02:57.097+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:57.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.045 seconds
[2023-10-14T11:02:58.128+0000] {processor.py:157} INFO - Started process (PID=907) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:58.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:02:58.133+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:02:58.133+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:58.143+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:02:58.141+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:02:58.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:02:58.163+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.041 seconds
[2023-10-14T11:03:26.480+0000] {processor.py:157} INFO - Started process (PID=962) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:26.483+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:03:26.486+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:03:26.486+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:26.495+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:03:26.493+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:03:26.495+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:26.513+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.037 seconds
[2023-10-14T11:03:56.856+0000] {processor.py:157} INFO - Started process (PID=1017) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:56.857+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:03:56.859+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:03:56.859+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:56.863+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:03:56.862+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:03:56.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:56.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.025 seconds
[2023-10-14T11:03:57.875+0000] {processor.py:157} INFO - Started process (PID=1018) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:57.876+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:03:57.878+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:03:57.878+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:57.885+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:03:57.884+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:03:57.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:03:57.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.030 seconds
[2023-10-14T11:04:28.374+0000] {processor.py:157} INFO - Started process (PID=1073) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:04:28.375+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:04:28.376+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:04:28.376+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:04:28.381+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:04:28.379+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:04:28.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:04:28.393+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.021 seconds
[2023-10-14T11:04:58.677+0000] {processor.py:157} INFO - Started process (PID=1128) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:04:58.678+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:04:58.680+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:04:58.680+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:04:58.684+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:04:58.683+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:04:58.684+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:04:58.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.022 seconds
[2023-10-14T11:05:28.790+0000] {processor.py:157} INFO - Started process (PID=1183) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:05:28.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:05:28.794+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:05:28.794+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:05:28.802+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:05:28.800+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:05:28.803+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:05:28.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.047 seconds
[2023-10-14T11:05:58.890+0000] {processor.py:157} INFO - Started process (PID=1238) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:05:58.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:05:58.893+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:05:58.893+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:05:58.899+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:05:58.898+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ingester_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingester_dag.py", line 3, in <module>
    from airflow.hooks import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.hooks' (/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/__init__.py)
[2023-10-14T11:05:58.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:05:58.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.034 seconds
[2023-10-14T11:06:13.531+0000] {processor.py:157} INFO - Started process (PID=1248) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:06:13.533+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:06:13.535+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:13.535+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:06:13.546+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ingest_data']) retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:06:13.623+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:13.623+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-14T11:06:13.628+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:13.627+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-14T11:06:13.630+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:13.630+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-14T11:06:13.630+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:13.630+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T11:06:13.635+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:13.635+0000] {dag.py:2963} INFO - Creating ORM DAG for ingest_data
[2023-10-14T11:06:13.640+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:13.640+0000] {dag.py:3722} INFO - Setting next_dagrun for ingest_data to 2023-01-01T00:00:00+00:00, run_after=2023-01-02T00:00:00+00:00
[2023-10-14T11:06:13.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.124 seconds
[2023-10-14T11:06:38.304+0000] {processor.py:157} INFO - Started process (PID=1301) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:06:38.305+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:06:38.309+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:38.309+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:06:38.320+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ingest_data']) retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:06:38.333+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:38.333+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T11:06:38.350+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:06:38.350+0000] {dag.py:3722} INFO - Setting next_dagrun for ingest_data to 2023-01-01T00:00:00+00:00, run_after=2023-01-02T00:00:00+00:00
[2023-10-14T11:06:38.362+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.061 seconds
[2023-10-14T11:07:08.718+0000] {processor.py:157} INFO - Started process (PID=1360) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:07:08.724+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:07:08.743+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:07:08.742+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:07:08.770+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ingest_data']) retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:07:08.826+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:07:08.826+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T11:07:08.874+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:07:08.874+0000] {dag.py:3722} INFO - Setting next_dagrun for ingest_data to 2023-01-15T00:00:00+00:00, run_after=2023-01-16T00:00:00+00:00
[2023-10-14T11:07:08.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.204 seconds
[2023-10-14T11:07:39.889+0000] {processor.py:157} INFO - Started process (PID=1415) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:07:39.892+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:07:39.898+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:07:39.898+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:07:39.910+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ingest_data']) retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:07:39.931+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:07:39.930+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T11:07:39.956+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.075 seconds
[2023-10-14T11:08:10.086+0000] {processor.py:157} INFO - Started process (PID=1470) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:08:10.089+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:08:10.094+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:08:10.094+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:08:10.107+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ingest_data']) retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:08:10.128+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:08:10.128+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T11:08:10.154+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.076 seconds
[2023-10-14T11:08:40.620+0000] {processor.py:157} INFO - Started process (PID=1525) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:08:40.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:08:40.629+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:08:40.627+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:08:40.649+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ingest_data']) retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:08:40.687+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:08:40.687+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T11:08:40.720+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.105 seconds
[2023-10-14T11:09:11.146+0000] {processor.py:157} INFO - Started process (PID=1580) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:09:11.148+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:09:11.151+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:09:11.151+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:09:11.157+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ingest_data']) retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:09:11.174+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:09:11.174+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T11:09:11.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.058 seconds
[2023-10-14T11:09:41.545+0000] {processor.py:157} INFO - Started process (PID=1635) to work on /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:09:41.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingester_dag.py for tasks to queue
[2023-10-14T11:09:41.549+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:09:41.548+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:09:41.558+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ingest_data']) retrieved from /opt/airflow/dags/ingester_dag.py
[2023-10-14T11:09:41.576+0000] {logging_mixin.py:151} INFO - [2023-10-14T11:09:41.575+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-14T11:09:41.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingester_dag.py took 0.062 seconds
